# Generated by Django 3.2.5 on 2021-07-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sem',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('sem_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
