# Generated by Django 2.2.14 on 2021-07-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_pdf',
            fields=[
                ('pdf_file', models.FileField(blank=True, upload_to='static')),
                ('pdf_name', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.course')),
            ],
        ),
    ]
