# Generated by Django 2.2.14 on 2021-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0002_course_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_pdf',
            name='ccid',
            field=models.IntegerField(default=0),
        ),
    ]
