# Generated by Django 2.2.14 on 2021-07-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0003_course_pdf_ccid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_pdf',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='static/all_pdf'),
        ),
    ]
