# Generated by Django 3.2.3 on 2021-07-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0004_auto_20210717_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='myhome/static/all_images'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course_pdf',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='myhome/static/all_pdf'),
        ),
    ]
