# Generated by Django 3.2.3 on 2021-07-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0005_auto_20210717_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
